/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Used to throw exceptions from the TriggerManager.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Michael Libman <Mike@Arketek.ca>
* @modifiedBy     Michael Libman <Mike@Arketek.ca>
* @maintainedBy   Michael Libman <Mike@Arketek.ca>
* @version        1.0
* @created        2019-04-18
* @modified       2019-04-18
* @systemLayer    Exception
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            Mike@Arketek.ca
* 2019-04-18      + Created the TriggerManagerException.
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public class TriggerManagerException extends Exception {}